// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.landvaluationsystem.rw/support",
            "email": "support@landvaluationsystem.rw"
        },
        "license": {
            "name": "Proprietary",
            "url": "http://www.landvaluationsystem.rw/license"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/audit-logs": {
            "get": {
                "responses": {}
            }
        },
        "/admin/config": {
            "get": {
                "responses": {}
            },
            "put": {
                "responses": {}
            }
        },
        "/admin/content/{id}/moderate": {
            "post": {
                "responses": {}
            }
        },
        "/admin/health": {
            "get": {
                "responses": {}
            }
        },
        "/admin/notifications": {
            "post": {
                "responses": {}
            }
        },
        "/admin/properties/{id}/approve": {
            "post": {
                "responses": {}
            }
        },
        "/admin/properties/{id}/reject": {
            "post": {
                "responses": {}
            }
        },
        "/admin/subscriptions": {
            "get": {
                "responses": {}
            }
        },
        "/admin/users": {
            "get": {
                "responses": {}
            }
        },
        "/admin/users/{id}": {
            "get": {
                "responses": {}
            }
        },
        "/admin/users/{id}/reactivate": {
            "post": {
                "responses": {}
            }
        },
        "/admin/users/{id}/suspend": {
            "post": {
                "responses": {}
            }
        },
        "/admin/users/{id}/verify-kyc": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Approve or reject the KYC verification submitted by a user (admin only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Verify user KYC (Admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "KYC verification decision",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.VerifyKYCRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "KYC verified",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or validation failed",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Admin access required",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "404": {
                        "description": "User or KYC not found",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    }
                }
            }
        },
        "/analytics/activity-report": {
            "get": {
                "responses": {}
            }
        },
        "/analytics/dashboard": {
            "get": {
                "responses": {}
            }
        },
        "/analytics/export": {
            "post": {
                "responses": {}
            }
        },
        "/analytics/heatmap": {
            "get": {
                "responses": {}
            }
        },
        "/analytics/market-trends": {
            "get": {
                "responses": {}
            }
        },
        "/analytics/properties/{id}": {
            "get": {
                "responses": {}
            }
        },
        "/analytics/revenue": {
            "get": {
                "responses": {}
            }
        },
        "/analytics/searches": {
            "get": {
                "responses": {}
            }
        },
        "/analytics/valuation-insights": {
            "get": {
                "responses": {}
            }
        },
        "/api/v1/exchange-rate": {
            "get": {
                "description": "Returns live exchange rate information for USD and RWF",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "currency"
                ],
                "summary": "Get current USD/RWF exchange rate",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/exchange-rate/convert": {
            "get": {
                "description": "Convert an amount from one currency to another",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "currency"
                ],
                "summary": "Convert between USD and RWF",
                "parameters": [
                    {
                        "type": "number",
                        "description": "Amount to convert",
                        "name": "amount",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Source currency (USD or RWF)",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Target currency (USD or RWF)",
                        "name": "to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/exchange-rate/refresh": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Force refresh of the cached exchange rate",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "currency"
                ],
                "summary": "Refresh exchange rate cache",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/properties": {
            "get": {
                "responses": {}
            },
            "post": {
                "responses": {}
            }
        },
        "/api/v1/properties/search": {
            "post": {
                "description": "Search for properties near a location with optional filters for price, type, and district",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "properties"
                ],
                "summary": "Search properties by location and filters",
                "parameters": [
                    {
                        "description": "Search filters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.PropertySearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Properties found",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/properties/stats": {
            "get": {
                "responses": {}
            }
        },
        "/api/v1/properties/{id}": {
            "get": {
                "responses": {}
            },
            "put": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            }
        },
        "/api/v1/valuations": {
            "get": {
                "description": "Get a list of all valuations created by the authenticated user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "valuations"
                ],
                "summary": "List user's valuations",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/handlers.ValuationResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Calculate estimated property value based on location, size, and type",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "valuations"
                ],
                "summary": "Calculate property valuation",
                "parameters": [
                    {
                        "description": "Valuation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateValuationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.ValuationResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/valuations/{id}": {
            "get": {
                "description": "Retrieve a specific valuation result by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "valuations"
                ],
                "summary": "Get valuation by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Valuation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.ValuationResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    }
                }
            }
        },
        "/auth/2fa/enable": {
            "post": {
                "responses": {}
            }
        },
        "/auth/2fa/verify": {
            "post": {
                "responses": {}
            }
        },
        "/auth/forgot-password": {
            "post": {
                "responses": {}
            }
        },
        "/auth/login": {
            "post": {
                "responses": {}
            }
        },
        "/auth/logout": {
            "post": {
                "responses": {}
            }
        },
        "/auth/refresh": {
            "post": {
                "responses": {}
            }
        },
        "/auth/register": {
            "post": {
                "responses": {}
            }
        },
        "/auth/resend-activation": {
            "post": {
                "responses": {}
            }
        },
        "/auth/resend-otp": {
            "post": {
                "responses": {}
            }
        },
        "/auth/reset-password": {
            "post": {
                "responses": {}
            }
        },
        "/auth/verify-email": {
            "post": {
                "responses": {}
            }
        },
        "/auth/verify-otp": {
            "post": {
                "responses": {}
            }
        },
        "/marketplace/properties-for-sale": {
            "get": {
                "responses": {}
            }
        },
        "/payments/callback": {
            "post": {
                "description": "Process payment provider callbacks (webhook)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Handle payment callback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Payment provider (mtn|airtel)",
                        "name": "provider",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Callback payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Callback processed",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid callback",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    }
                }
            }
        },
        "/payments/mobile-money": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Initiate a payment via MTN or Airtel mobile money with validation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Initiate mobile money payment",
                "parameters": [
                    {
                        "description": "Payment request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.MobileMoneyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Payment initiated",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or validation failed",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    }
                }
            }
        },
        "/payments/{transaction_id}/status": {
            "get": {
                "description": "Retrieve the current status of a payment transaction",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Check payment status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction ID",
                        "name": "transaction_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Payment provider (mtn|airtel)",
                        "name": "provider",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Payment status retrieved",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Transaction not found",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    }
                }
            }
        },
        "/properties/{id}/marketplace-listings": {
            "get": {
                "responses": {}
            }
        },
        "/properties/{id}/sync-marketplace": {
            "post": {
                "responses": {}
            }
        },
        "/subscriptions/billing-history": {
            "get": {
                "responses": {}
            }
        },
        "/subscriptions/billing-info": {
            "put": {
                "responses": {}
            }
        },
        "/subscriptions/cancel": {
            "post": {
                "responses": {}
            }
        },
        "/subscriptions/current": {
            "get": {
                "responses": {}
            }
        },
        "/subscriptions/downgrade": {
            "post": {
                "responses": {}
            }
        },
        "/subscriptions/invoices/{id}": {
            "get": {
                "responses": {}
            }
        },
        "/subscriptions/plans": {
            "get": {
                "responses": {}
            }
        },
        "/subscriptions/upgrade": {
            "post": {
                "responses": {}
            }
        },
        "/users/account": {
            "delete": {
                "responses": {}
            }
        },
        "/users/account-settings": {
            "get": {
                "responses": {}
            },
            "put": {
                "responses": {}
            }
        },
        "/users/activity": {
            "get": {
                "responses": {}
            }
        },
        "/users/change-password": {
            "post": {
                "responses": {}
            }
        },
        "/users/kyc": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Submit Know Your Customer identity verification documents (national ID, birth certificate, etc.)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kyc"
                ],
                "summary": "Submit KYC documentation",
                "parameters": [
                    {
                        "description": "KYC submission",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.SubmitKYCRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "KYC submitted successfully",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or validation failed",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    }
                }
            }
        },
        "/users/kyc/status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve the current KYC verification status and submission details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kyc"
                ],
                "summary": "Get KYC verification status",
                "responses": {
                    "200": {
                        "description": "KYC status retrieved",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "404": {
                        "description": "KYC not found",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    }
                }
            }
        },
        "/users/notifications": {
            "get": {
                "responses": {}
            }
        },
        "/users/notifications/{id}/read": {
            "post": {
                "responses": {}
            }
        },
        "/users/profile": {
            "get": {
                "responses": {}
            },
            "put": {
                "responses": {}
            }
        }
    },
    "definitions": {
        "handlers.CreateValuationRequest": {
            "type": "object",
            "required": [
                "district",
                "property_size_sqm",
                "property_type"
            ],
            "properties": {
                "district": {
                    "type": "string"
                },
                "include_comparables": {
                    "type": "boolean"
                },
                "include_factors": {
                    "type": "boolean"
                },
                "property_size_sqm": {
                    "type": "number"
                },
                "property_type": {
                    "type": "string",
                    "enum": [
                        "residential",
                        "commercial",
                        "agricultural",
                        "industrial"
                    ]
                },
                "sector": {
                    "type": "string"
                }
            }
        },
        "handlers.MobileMoneyRequest": {
            "type": "object",
            "required": [
                "amount",
                "phone_number",
                "provider"
            ],
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 50000
                },
                "description": {
                    "type": "string",
                    "example": "Property payment"
                },
                "phone_number": {
                    "type": "string",
                    "example": "+250788123456"
                },
                "provider": {
                    "type": "string",
                    "enum": [
                        "mtn",
                        "airtel"
                    ],
                    "example": "mtn"
                }
            }
        },
        "handlers.PropertySearchRequest": {
            "type": "object",
            "required": [
                "latitude",
                "longitude"
            ],
            "properties": {
                "district": {
                    "type": "string",
                    "example": "Kigali"
                },
                "latitude": {
                    "type": "number",
                    "example": -1.9536
                },
                "longitude": {
                    "type": "number",
                    "example": 29.8739
                },
                "max_price": {
                    "type": "number",
                    "example": 10000000
                },
                "max_size": {
                    "type": "number",
                    "example": 1000
                },
                "min_price": {
                    "type": "number",
                    "example": 1000000
                },
                "min_size": {
                    "type": "number",
                    "example": 100
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "page_size": {
                    "type": "integer",
                    "example": 50
                },
                "property_type": {
                    "type": "string",
                    "example": "residential"
                },
                "radius": {
                    "type": "number",
                    "example": 5000
                },
                "sort_by": {
                    "type": "string",
                    "example": "created_at"
                },
                "sort_order": {
                    "type": "string",
                    "example": "desc"
                }
            }
        },
        "handlers.PropertySummary": {
            "type": "object",
            "properties": {
                "district": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "land_size": {
                    "type": "number"
                },
                "price": {
                    "type": "number"
                },
                "property_type": {
                    "type": "string"
                },
                "sector": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "handlers.SubmitKYCRequest": {
            "type": "object",
            "required": [
                "document_type",
                "document_url",
                "first_name",
                "last_name",
                "national_id"
            ],
            "properties": {
                "document_type": {
                    "type": "string",
                    "enum": [
                        "national_id",
                        "birth_certificate",
                        "passport",
                        "driver_license"
                    ],
                    "example": "national_id"
                },
                "document_url": {
                    "type": "string",
                    "example": "https://example.com/doc.pdf"
                },
                "first_name": {
                    "type": "string",
                    "minLength": 2,
                    "example": "John"
                },
                "last_name": {
                    "type": "string",
                    "minLength": 2,
                    "example": "Doe"
                },
                "national_id": {
                    "type": "string",
                    "maxLength": 30,
                    "minLength": 6,
                    "example": "1ABCDE1234567890"
                }
            }
        },
        "handlers.ValuationResponse": {
            "type": "object",
            "properties": {
                "adjustments": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number",
                        "format": "float64"
                    }
                },
                "base_price": {
                    "type": "number"
                },
                "comparables": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.PropertySummary"
                    }
                },
                "confidence": {
                    "type": "number"
                },
                "confidence_level": {
                    "type": "string"
                },
                "estimated_value_rwf": {
                    "type": "number"
                },
                "factors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ValuationFactor"
                    }
                },
                "gazette_reference": {
                    "type": "string"
                },
                "recommendations": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "zone_coefficient": {
                    "type": "number"
                }
            }
        },
        "handlers.VerifyKYCRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "comment": {
                    "type": "string",
                    "maxLength": 500,
                    "example": "All documents verified successfully"
                },
                "reason": {
                    "type": "string",
                    "example": "Invalid national ID format"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "approved",
                        "rejected",
                        "pending"
                    ],
                    "example": "approved"
                }
            }
        },
        "models.ValuationFactor": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "impact": {
                    "description": "positive, negative, neutral",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "utils.APIError": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "utils.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/utils.APIError"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "api.landvaluationsystem.rw",
	BasePath:         "/api/v1",
	Schemes:          []string{"https", "http"},
	Title:            "Land Valuation System API",
	Description:      "Rwanda Land Valuation System with Official Gazette Integration",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
